### ISSUE TITLE
Criar conexão entre pessoas

### ISSUE THREAD

**Issue by isaacmsl** [isaacmsl/bora-pagar#13]
![Image](https://github.com/isaacmsl/bora-pagar/assets/31693006/6475437d-0b3c-4511-86a8-5c1fdfb2e3a5)

[Requisito](https://github.com/isaacmsl/bora-pagar/wiki/Criar-conex%C3%A3o-entre-pessoas)

# Backend

- [x] Teste de conexão entre usuários
- [x] Nova propriedade do usuário `connections`
- [x] Rota para criar conexão entre o usuário logado com outra pessoa

# Frontend

- [x] Página para buscar pessoas
- [x] Botão para conectar pessoas
- [ ] Integrar com o backend

**Comment by isaacmsl** [comment]
`connections` or `friends`?

**Comment by Kywal** [comment]
decidi colocar `friends` pra influenciar o front a fazer o mesmo, parece mais caloroso, menos formal.
