### ISSUE TITLE
(bug) Pages menu bar gets higher than expected

### ISSUE THREAD

**Issue by Kywal** [isaacmsl/bora-pagar#139]
**Descrição do bug**

Quando a label `Campos de busca` é minimizado o menu de páginas sobe, desajustando o equilíbrio de espaço tomado por cada componente.

**Como reproduzir**

Passo a passo:

1. Clique na label `Campos de busca`

**O que é esperado**

O menu das páginas deve ficar próximo da base/footer da tela.

**Screenshots**

<img width="200em" height="400em" src="https://github.com/isaacmsl/bora-pagar/assets/69535401/ea34b786-eaba-4498-b47d-74c45ccf16bf">

**Comment by isaacmsl** [comment]
@IanGabriel12 percebes que o conteúdo das disciplinas está muito pequeno? Quase não há o que scrollar. Acho que resolver isso acaba resolvendo esta issue.

**Comment by isaacmsl** [comment]
![image](https://github.com/isaacmsl/bora-pagar/assets/31693006/43d83599-b938-416a-bf48-91a2b3c41cb4)

Em desktop também! Precisamos rever isso.
