### ISSUE TITLE
(bug) Button `pagarei/não pagarei` gets unaligned

### ISSUE THREAD

**Issue by Kywal** [isaacmsl/bora-pagar#145]
**Descrição do bug**

Botão `pagarei/não pagarei` fica desalinhado a depender da quantidade de pessoas interessadas.

**Como reproduzir**

Passo a passo:

1. Verifique disciplinas com diferentes quantidades de interessados.

**O que é esperado**

Os botões devem permanecer alinhados independentemente da quantidade de pessoas inscritas.

**Screenshots**

![image](https://github.com/isaacmsl/bora-pagar/assets/69535401/d9a78412-3e38-46f7-ac93-f7d2208ccbca)

**Comment by isaacmsl** [comment]
Problema muito básico de se resolver acredito. Talvez um `justify-content: end` num pai que tenha `display: flex`.
Consegues resolver, @Kywal ?

**Comment by Kywal** [comment]
Acredito que sim, me atribuí justamente por conta disso. Vou tentar aqui.
