### ISSUE TITLE
(feat) Títulos das disciplinas com ellipsis

### ISSUE THREAD

**Issue by isaacmsl** [isaacmsl/bora-pagar#152]
**Motivo**

Muitas disciplinas possuem títulos enormes e isso acaba gerando um transtorno na visualização do conteúdo: às vezes é tão grande que sobresai do component pai e acaba gerando problemas de acessibilidade.

**Objetivo**

Estilizar o component `SubjectListItem` definindo um tamanho máximo para se considerar o título de uma disciplina e então fazer algo com `DIM0000 - TENHO MUITOS CARACTE...`.  Não sei se tem algo pronto do `vuetify` para isso, mas há um tutorial muito simples: ellipsis

**Descreva alternativas que você considerou**

Nenhuma.

**Comment by Pablo1Gustavo** [comment]
Basta definir um width no elemento do titulo e usar a classe já pronta do vuetify "text-truncate"
