### ISSUE TITLE
(bug) router.push na tela de disciplinas de usuário

### ISSUE THREAD

**Issue by isaacmsl** [isaacmsl/bora-pagar#154]
**Descrição do bug**

Se você já estiver na tela de disciplinas de um usuário, não pode ir diretamente para a tela de disciplinas de outro usuário.

**Como reproduzir**

Passo a passo:

1. Clique nas disciplinas que você vai pagar
1. Alguma disciplina sua deve ter outra pessoa que também quer pagar
1. Clique na foto da outra pessoa
1. Apesar da rota ter alterado, você ainda continua vendo suas disciplinas

**O que é esperado**

Você deveria ver as disciplinas do outro usuário.

**Screenshots**

https://github.com/isaacmsl/bora-pagar/assets/31693006/d8c53d36-bcea-4507-a594-7ec2dc1e7a0e

**Conteúdo adicional**

Talvez seja necessário usar a função de `computed` em alguma propriedade de referência na página de `SubjectsUser`. Parece que não está havendo uma atualização desse usuário no estado.

**Comment by IanGabriel12** [comment]
Todos os seus vídeos dão como corrompidos para mim
