### ISSUE TITLE
(bug) Erro no teste `shoudFindByGoogleId`

### ISSUE THREAD

**Issue by RamonJales** [isaacmsl/bora-pagar#172]
**Descrição do bug**

O shoudFindByGoogleId retorna um erro `IncorrectResultSizeDataAccessException`.

**Como reproduzir**

- Vá em `bora-pagar/backend/src/test/java/ufrn/imd/boraPagar/user`
- Rode o test `shoudFindByGoogleId`

**O que é esperado**

Retornar o usuário do `googleId` correspondente

**Screenshots**
![Captura de tela de 2024-01-13 22-35-11](https://github.com/isaacmsl/bora-pagar/assets/85131757/e999a16e-4176-4162-94b8-c791913ccdad)

**Comment by isaacmsl** [comment]
Vai ser resolvido na PR #150 .

**Comment by isaacmsl** [comment]
Já foi resolvida.
