### ISSUE TITLE
(feat) Github Action verifica testes

### ISSUE THREAD

**Issue by isaacmsl** [isaacmsl/bora-pagar#173]
**Motivo**

Quando o Github verificar um novo commit em um dos serviços (back, front), ele realiza os testes da aplicação para conferir se está tudo ok. Dessa forma conseguimos controlar as PRs que possuem algum bug e não passa nos testes.

**Objetivo**

Melhorar a qualidade do código.

**Descreva alternativas que você considerou**

Nenhuma.

**Conteúdo adicional**

Ainda tem como criar essa Github Action? :eyes: 
Será que vamos precisar migrar pro Gitlab só para ter mais poderes?

**Comment by RamonJales** [comment]
Nossa, não sabia que tinha como fazer isso. Irei dá uma pesquisada

**Comment by isaacmsl** [comment]
Tem sim. 
https://github.com/isaacmsl/bora-pagar/actions/new

**Comment by isaacmsl** [comment]
Consigo acessar, não sei vocês como contribuidores.
