### ISSUE TITLE
(bug) Click user photo to user subjects not working

### ISSUE THREAD

**Issue by isaacmsl** [isaacmsl/bora-pagar#176]
**Description**

Even that was a problem solved in #161 , now it returns.

**How to reproduce**

Steps:

1. Log in
1. Click on "Pagarei" button
1. Click in somebody photo that will pay with the user

**What's expected**

Do not render the page to the clicked user. Like was happing in problem solved at #161 .

**Screenshots**

https://youtu.be/YU5goOjOwk8

**Comment by IanGabriel12** [comment]
O bug antes era que quando o id era atualizado na rota, a tela não atualizada. Agora, pelo seu vídeo, parece que é o id que não está mudando. Vou dar uma olhada.

**Comment by isaacmsl** [comment]
Faz sentido! Deve ser algum problema no roteamento para a página. Tomando `undefined` no googleId talvez?

**Comment by isaacmsl** [comment]
What?! Tá funcionando aqui em produção. '-'

**Comment by isaacmsl** [comment]
Só funciona no "Pagarei". Quando você clica através de "Amigos" e tenta alterar que não funciona.

**Comment by IanGabriel12** [comment]
O bug só ocorre quando tem mais de 3 pessoas na matéria, pois infelizmente só coloquei o @click no caso que tem menos de 3 pessoas. Vou componentizar a imagem para evitar este tipo de bug no futuro
