### ISSUE TITLE
(feat) Implementar Role no model User

### ISSUE THREAD

**Issue by RamonJales** [isaacmsl/bora-pagar#37]
**Motivo**

Alguns usuários não terão acesso a certos endpoints, para restringir esse acesso devemos implementar as Role.

**Objetivo**

Segurança da aplicação.

**Comment by isaacmsl** [comment]
Por padrão todas as que precisam de verificação de autenticação fazem sentido verificar também se possuem a role de ADMIN. Salvo me engano no futuro alguma relacionada a disciplinas vai usar autenticação também mas não precisa verificar se é ADMIN. Olhe #33 .
