### ISSUE TITLE
(feat) Paginação no findAll das disciplinas

### ISSUE THREAD

**Issue by isaacmsl** [isaacmsl/bora-pagar#41]
**Motivo**

Ao todo são 46k disciplinas e isso representa uma quantidade considerável de MB. Dessa forma, uma requisição que busca sempre todas as disciplinas acaba sendo muito custoso para o usuário.

**Objetivo**

Paginar o endpoint de find da entidade de disciplinas. 

**Descreva alternativas que você considerou**

Uma forma de não se preocupar com isso é utilizando cache no frontend ou backend, isto é, deixamos a resposta desse endpoint em cache por um determinado tempo (a cada um dia? tendo em vista que essas disciplinas não mudam tanto assim). Dessa forma, o usuário, mesmo que 46k disciplinas, a resposta bem mais rápido.

**Conteúdo adicional**

Um tutorial de paginação: https://medium.com/@miguel.duque7/how-to-paginate-and-sort-a-spring-boot-rest-api-with-mongodb-nosql-database-935e8bac6e87

Spring Cache: https://www.youtube.com/watch?v=YcI9b-lgi7w

**Comment by isaacmsl** [comment]
O cache é incrível. Isso pode ser a solução mais simples para agora. Não precisamos necessariamente paginar. Talvez o problema é que ainda são 50MB. O **frontend** precisa testar isso. Vou mandar uma branch.

**Comment by isaacmsl** [comment]
![image](https://github.com/isaacmsl/bora-pagar/assets/31693006/bbf612eb-22db-4dc5-8dd3-592325cab28a)

O tempo está em segundos. Com certeza vale muita a pena colocarmos cache pelo menos nessa rota que é mais importante para a aplicação e será a mais utilizada.

**Comment by isaacmsl** [comment]
A paginação também pode ser feita de maneira muito simples. Por favor seguir o exemplo:

https://www.youtube.com/watch?v=Jrhb5YJK5II

**Comment by RamonJales** [comment]
Um meio para  fazer a paginação é: fazer com que nosso `subjectRepository` estenda a interface `PagingAndSortingRepository` e, assim, herdar o findAll "paginado".

**Comment by RamonJales** [comment]
Não foi necessário que o nosso `repository` estendesse o `PagingAndSortingRepository`, pois o ` spring-boot-starter-data-mongodb` suporta o método `findAll` com o parâmetro do tipo `Pageable`. Apenas nosso repository precisa estender o `MongoRepository`

**Comment by RamonJales** [comment]
Nosso controller do `findAll` não retorna mais um ResponseEntity, mas sim um `Page<?>`

**Comment by RamonJales** [comment]
Tive algumas **confusões** ao tentar implementar a paginação com esse projeto, pois temos um conjunto de classes bases(as `core`) e a sobrescrita do método findAll para que ele não necessite de uma `credential`.
